export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_ALL_COUNTRIES_SUCCESS = "GET_ALL_COUNTRIES_SUCCESS";
export const GET_ALL_COUNTRIES_FAIL = "GET_ALL_COUNTRIES_FAIL";

export const SWITCH_COLOR_MODE = "SWITCH_COLOR_MODE";

export const GET_SINGLE_COUNTRIES = "GET_SINGLE_COUNTRIES";
export const GET_SINGLE_COUNTRIES_SUCCESS = "GET_SINGLE_COUNTRIES_SUCCESS";
export const GET_SINGLE_COUNTRIES_FAIL = "GET_SINGLE_COUNTRIES_FAIL";

